version: '3.8'

services:
  couchbase:
    image: couchbase:latest
    container_name: couchbase
    ports:
      - "8091-8094:8091-8094" # Admin Console, REST API, and Couchbase Views
      - "11210-11211:11210-11211" # Data and Index services
    environment:
      COUCHBASE_ADMIN_USERNAME: admin
      COUCHBASE_ADMIN_PASSWORD: password
    volumes:
      - couchbase_data:/opt/couchbase/var

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  couchbase_data:
    driver: local
  postgres_data:
    driver: local